# Usa una imagen oficial de Node.js (versión fija)
#FROM node:18-alpine
FROM node:23-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia solo los archivos esenciales para la instalación de dependencias
COPY volumes/frontend/package*.json .

# Instala las dependencias
RUN npm install

# Copia el código fuente
#COPY volumes/frontend/ .

# Exponer el puerto para Vite/React (desde el .env)
EXPOSE ${FRONTEND_PORT_INTERNAL}

# Iniciar el servidor en modo desarrollo
CMD ["sh", "-c", "npm run dev -- --host ${FRONTEND_HOST} --port ${FRONTEND_PORT_INTERNAL}"]
