TYPE=VIEW
query=select `f`.`id` AS `id`,`f`.`uuid` AS `uuid`,`f`.`title` AS `title`,`f`.`description` AS `description`,`f`.`category_id` AS `category_id`,`f`.`subcategory_id` AS `subcategory_id`,`f`.`visibility` AS `visibility`,`f`.`allow_anonymous` AS `allow_anonymous`,`f`.`require_institutional_email` AS `require_institutional_email`,`f`.`limit_one_response` AS `limit_one_response`,`f`.`require_signature` AS `require_signature`,`f`.`deadline` AS `deadline`,`f`.`deadline_time` AS `deadline_time`,`f`.`version_number` AS `version_number`,`f`.`parent_form_id` AS `parent_form_id`,`f`.`draft_data` AS `draft_data`,`f`.`preview_config` AS `preview_config`,`f`.`additional_options` AS `additional_options`,`f`.`status_id` AS `status_id`,`f`.`created_by` AS `created_by`,`f`.`created_at` AS `created_at`,`f`.`updated_at` AS `updated_at`,`f`.`last_preview_at` AS `last_preview_at`,`f`.`start_date` AS `start_date`,`f`.`end_date` AS `end_date`,`c`.`name` AS `category_name`,`sc`.`name` AS `subcategory_name`,`u`.`full_name` AS `created_by_name`,`st`.`name` AS `status_name`,count(distinct `fp`.`user_id`) AS `assigned_users`,count(distinct `fr`.`id`) AS `total_responses`,round(count(distinct `fr`.`id`) * 100.0 / nullif(count(distinct `fp`.`user_id`),0),2) AS `response_rate` from ((((((`nokto_db`.`forms` `f` join `nokto_db`.`categories` `c` on(`f`.`category_id` = `c`.`id`)) left join `nokto_db`.`subcategories` `sc` on(`f`.`subcategory_id` = `sc`.`id`)) join `nokto_db`.`users` `u` on(`f`.`created_by` = `u`.`id`)) join `nokto_db`.`status_types` `st` on(`f`.`status_id` = `st`.`id`)) left join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) where `f`.`status_id` in (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` in (\'active\',\'published\')) group by `f`.`id`
md5=a6eb49e8aea4f1ad9b583913fba86ed6
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001747614996164094
create-version=2
source=SELECT f.*,\n    c.name as category_name,\n    sc.name as subcategory_name,\n    u.full_name as created_by_name,\n    st.name as status_name,\n    COUNT(DISTINCT fp.user_id) as assigned_users,\n    COUNT(DISTINCT fr.id) as total_responses,\n    ROUND(\n        COUNT(DISTINCT fr.id) * 100.0 / NULLIF(COUNT(DISTINCT fp.user_id), 0),\n        2\n    ) as response_rate\nFROM forms f\n    JOIN categories c ON f.category_id = c.id\n    LEFT JOIN subcategories sc ON f.subcategory_id = sc.id\n    JOIN users u ON f.created_by = u.id\n    JOIN status_types st ON f.status_id = st.id\n    LEFT JOIN form_permissions fp ON f.id = fp.form_id\n    LEFT JOIN form_responses fr ON f.id = fr.form_id\nWHERE f.status_id IN (\n        SELECT id\n        FROM status_types\n        WHERE code IN (\'active\', \'published\')\n    )\nGROUP BY f.id
client_cs_name=utf8mb3
connection_cl_name=utf8mb3_general_ci
view_body_utf8=select `f`.`id` AS `id`,`f`.`uuid` AS `uuid`,`f`.`title` AS `title`,`f`.`description` AS `description`,`f`.`category_id` AS `category_id`,`f`.`subcategory_id` AS `subcategory_id`,`f`.`visibility` AS `visibility`,`f`.`allow_anonymous` AS `allow_anonymous`,`f`.`require_institutional_email` AS `require_institutional_email`,`f`.`limit_one_response` AS `limit_one_response`,`f`.`require_signature` AS `require_signature`,`f`.`deadline` AS `deadline`,`f`.`deadline_time` AS `deadline_time`,`f`.`version_number` AS `version_number`,`f`.`parent_form_id` AS `parent_form_id`,`f`.`draft_data` AS `draft_data`,`f`.`preview_config` AS `preview_config`,`f`.`additional_options` AS `additional_options`,`f`.`status_id` AS `status_id`,`f`.`created_by` AS `created_by`,`f`.`created_at` AS `created_at`,`f`.`updated_at` AS `updated_at`,`f`.`last_preview_at` AS `last_preview_at`,`f`.`start_date` AS `start_date`,`f`.`end_date` AS `end_date`,`c`.`name` AS `category_name`,`sc`.`name` AS `subcategory_name`,`u`.`full_name` AS `created_by_name`,`st`.`name` AS `status_name`,count(distinct `fp`.`user_id`) AS `assigned_users`,count(distinct `fr`.`id`) AS `total_responses`,round(count(distinct `fr`.`id`) * 100.0 / nullif(count(distinct `fp`.`user_id`),0),2) AS `response_rate` from ((((((`nokto_db`.`forms` `f` join `nokto_db`.`categories` `c` on(`f`.`category_id` = `c`.`id`)) left join `nokto_db`.`subcategories` `sc` on(`f`.`subcategory_id` = `sc`.`id`)) join `nokto_db`.`users` `u` on(`f`.`created_by` = `u`.`id`)) join `nokto_db`.`status_types` `st` on(`f`.`status_id` = `st`.`id`)) left join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) where `f`.`status_id` in (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` in (\'active\',\'published\')) group by `f`.`id`
mariadb-version=100621
