TYPE=VIEW
query=select `f`.`id` AS `id`,`f`.`title` AS `title`,`f`.`deadline` AS `deadline`,`f`.`deadline_time` AS `deadline_time`,to_days(`f`.`deadline`) - to_days(curdate()) AS `days_until_deadline`,count(distinct `fp`.`user_id`) AS `assigned_users`,count(distinct `fr`.`id`) AS `responses_received`,count(distinct `fp`.`user_id`) - count(distinct `fr`.`user_id`) AS `pending_responses`,case when to_days(`f`.`deadline`) - to_days(curdate()) < 0 then \'Vencido\' when to_days(`f`.`deadline`) - to_days(curdate()) = 0 then \'Vence hoy\' when to_days(`f`.`deadline`) - to_days(curdate()) <= 3 then \'Crítico\' when to_days(`f`.`deadline`) - to_days(curdate()) <= 7 then \'Próximo a vencer\' else \'En tiempo\' end AS `urgency_status` from ((`nokto_db`.`forms` `f` left join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) where `f`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') and `f`.`deadline` is not null group by `f`.`id` having `days_until_deadline` >= -30
md5=2c7ca54bd9a95834923b8d0606bd746a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001747614996357940
create-version=2
source=SELECT f.id,\n    f.title,\n    f.deadline,\n    f.deadline_time,\n    DATEDIFF(f.deadline, CURRENT_DATE) as days_until_deadline,\n    COUNT(DISTINCT fp.user_id) as assigned_users,\n    COUNT(DISTINCT fr.id) as responses_received,\n    COUNT(DISTINCT fp.user_id) - COUNT(DISTINCT fr.user_id) as pending_responses,\n    CASE\n        WHEN DATEDIFF(f.deadline, CURRENT_DATE) < 0 THEN \'Vencido\'\n        WHEN DATEDIFF(f.deadline, CURRENT_DATE) = 0 THEN \'Vence hoy\'\n        WHEN DATEDIFF(f.deadline, CURRENT_DATE) <= 3 THEN \'Crítico\'\n        WHEN DATEDIFF(f.deadline, CURRENT_DATE) <= 7 THEN \'Próximo a vencer\'\n        ELSE \'En tiempo\'\n    END as urgency_status\nFROM forms f\n    LEFT JOIN form_permissions fp ON f.id = fp.form_id\n    LEFT JOIN form_responses fr ON f.id = fr.form_id\nWHERE f.status_id = (\n        SELECT id\n        FROM status_types\n        WHERE code = \'published\'\n    )\n    AND f.deadline IS NOT NULL\nGROUP BY f.id\nHAVING days_until_deadline >= -30
client_cs_name=utf8mb3
connection_cl_name=utf8mb3_general_ci
view_body_utf8=select `f`.`id` AS `id`,`f`.`title` AS `title`,`f`.`deadline` AS `deadline`,`f`.`deadline_time` AS `deadline_time`,to_days(`f`.`deadline`) - to_days(curdate()) AS `days_until_deadline`,count(distinct `fp`.`user_id`) AS `assigned_users`,count(distinct `fr`.`id`) AS `responses_received`,count(distinct `fp`.`user_id`) - count(distinct `fr`.`user_id`) AS `pending_responses`,case when to_days(`f`.`deadline`) - to_days(curdate()) < 0 then \'Vencido\' when to_days(`f`.`deadline`) - to_days(curdate()) = 0 then \'Vence hoy\' when to_days(`f`.`deadline`) - to_days(curdate()) <= 3 then \'Crítico\' when to_days(`f`.`deadline`) - to_days(curdate()) <= 7 then \'Próximo a vencer\' else \'En tiempo\' end AS `urgency_status` from ((`nokto_db`.`forms` `f` left join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) where `f`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') and `f`.`deadline` is not null group by `f`.`id` having `days_until_deadline` >= -30
mariadb-version=100621
