TYPE=VIEW
query=select `f`.`id` AS `form_id`,`f`.`title` AS `title`,count(`fr`.`id`) AS `total_responses`,count(case when `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) AS `validated_responses`,count(case when `fr`.`manual_signature_key` is not null then 1 end) AS `signed_responses`,count(case when `fr`.`status_id` <> (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) AS `pending_validation`,round(count(case when `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) * 100.0 / nullif(count(`fr`.`id`),0),2) AS `validation_rate` from (`nokto_db`.`forms` `f` left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) group by `f`.`id`
md5=10844c12b29529cc138632efd47bce58
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001747614996499868
create-version=2
source=SELECT f.id as form_id,\n    f.title,\n    COUNT(fr.id) as total_responses,\n    COUNT(\n        CASE\n            WHEN fr.status_id = (\n                SELECT id\n                FROM status_types\n                WHERE code = \'published\'\n            ) THEN 1\n        END\n    ) as validated_responses,\n    COUNT(\n        CASE\n            WHEN fr.manual_signature_key IS NOT NULL THEN 1\n        END\n    ) as signed_responses,\n    COUNT(\n        CASE\n            WHEN fr.status_id != (\n                SELECT id\n                FROM status_types\n                WHERE code = \'published\'\n            ) THEN 1\n        END\n    ) as pending_validation,\n    ROUND(\n        COUNT(\n            CASE\n                WHEN fr.status_id = (\n                    SELECT id\n                    FROM status_types\n                    WHERE code = \'published\'\n                ) THEN 1\n            END\n        ) * 100.0 / NULLIF(COUNT(fr.id), 0),\n        2\n    ) as validation_rate\nFROM forms f\n    LEFT JOIN form_responses fr ON f.id = fr.form_id\nGROUP BY f.id
client_cs_name=utf8mb3
connection_cl_name=utf8mb3_general_ci
view_body_utf8=select `f`.`id` AS `form_id`,`f`.`title` AS `title`,count(`fr`.`id`) AS `total_responses`,count(case when `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) AS `validated_responses`,count(case when `fr`.`manual_signature_key` is not null then 1 end) AS `signed_responses`,count(case when `fr`.`status_id` <> (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) AS `pending_validation`,round(count(case when `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') then 1 end) * 100.0 / nullif(count(`fr`.`id`),0),2) AS `validation_rate` from (`nokto_db`.`forms` `f` left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) group by `f`.`id`
mariadb-version=100621
