TYPE=VIEW
query=select \'deadline_approaching\' AS `notification_type`,`f`.`id` AS `form_id`,`f`.`title` AS `title`,`u`.`id` AS `user_id`,`u`.`full_name` AS `full_name`,`u`.`email` AS `email`,`f`.`deadline` AS `relevant_date`,to_days(`f`.`deadline`) - to_days(curdate()) AS `days_remaining` from (((`nokto_db`.`forms` `f` join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) join `nokto_db`.`users` `u` on(`fp`.`user_id` = `u`.`id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id` and `u`.`id` = `fr`.`user_id`)) where `f`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') and `fr`.`id` is null and `f`.`deadline` >= curdate() and to_days(`f`.`deadline`) - to_days(curdate()) <= 7 union all select \'response_validation_needed\' AS `notification_type`,`f`.`id` AS `form_id`,`f`.`title` AS `title`,`u`.`id` AS `user_id`,`u`.`full_name` AS `full_name`,`u`.`email` AS `email`,`fr`.`submitted_at` AS `relevant_date`,to_days(curdate()) - to_days(`fr`.`submitted_at`) AS `days_pending` from ((`nokto_db`.`forms` `f` join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) join `nokto_db`.`users` `u` on(`f`.`created_by` = `u`.`id`)) where `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'pending\')
md5=2960358bee745cf9411f496c114c56f6
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001747614996521580
create-version=2
source=SELECT \'deadline_approaching\' as notification_type,\n    f.id as form_id,\n    f.title,\n    u.id as user_id,\n    u.full_name,\n    u.email,\n    f.deadline as relevant_date,\n    DATEDIFF(f.deadline, CURRENT_DATE) as days_remaining\nFROM forms f\n    JOIN form_permissions fp ON f.id = fp.form_id\n    JOIN users u ON fp.user_id = u.id\n    LEFT JOIN form_responses fr ON f.id = fr.form_id\n    AND u.id = fr.user_id\nWHERE f.status_id = (\n        SELECT id\n        FROM status_types\n        WHERE code = \'published\'\n    )\n    AND fr.id IS NULL\n    AND f.deadline >= CURRENT_DATE\n    AND DATEDIFF(f.deadline, CURRENT_DATE) <= 7\nUNION ALL\nSELECT \'response_validation_needed\' as notification_type,\n    f.id as form_id,\n    f.title,\n    u.id as user_id,\n    u.full_name,\n    u.email,\n    fr.submitted_at as relevant_date,\n    DATEDIFF(CURRENT_DATE, fr.submitted_at) as days_pending\nFROM forms f\n    JOIN form_responses fr ON f.id = fr.form_id\n    JOIN users u ON f.created_by = u.id\nWHERE fr.status_id = (\n        SELECT id\n        FROM status_types\n        WHERE code = \'pending\'\n    )
client_cs_name=utf8mb3
connection_cl_name=utf8mb3_general_ci
view_body_utf8=select \'deadline_approaching\' AS `notification_type`,`f`.`id` AS `form_id`,`f`.`title` AS `title`,`u`.`id` AS `user_id`,`u`.`full_name` AS `full_name`,`u`.`email` AS `email`,`f`.`deadline` AS `relevant_date`,to_days(`f`.`deadline`) - to_days(curdate()) AS `days_remaining` from (((`nokto_db`.`forms` `f` join `nokto_db`.`form_permissions` `fp` on(`f`.`id` = `fp`.`form_id`)) join `nokto_db`.`users` `u` on(`fp`.`user_id` = `u`.`id`)) left join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id` and `u`.`id` = `fr`.`user_id`)) where `f`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'published\') and `fr`.`id` is null and `f`.`deadline` >= curdate() and to_days(`f`.`deadline`) - to_days(curdate()) <= 7 union all select \'response_validation_needed\' AS `notification_type`,`f`.`id` AS `form_id`,`f`.`title` AS `title`,`u`.`id` AS `user_id`,`u`.`full_name` AS `full_name`,`u`.`email` AS `email`,`fr`.`submitted_at` AS `relevant_date`,to_days(curdate()) - to_days(`fr`.`submitted_at`) AS `days_pending` from ((`nokto_db`.`forms` `f` join `nokto_db`.`form_responses` `fr` on(`f`.`id` = `fr`.`form_id`)) join `nokto_db`.`users` `u` on(`f`.`created_by` = `u`.`id`)) where `fr`.`status_id` = (select `nokto_db`.`status_types`.`id` from `nokto_db`.`status_types` where `nokto_db`.`status_types`.`code` = \'pending\')
mariadb-version=100621
